"""Shared wire-format enums for FlowLens domain contracts."""

from enum import Enum


class SessionMode(str, Enum):
    """Supported session modes."""

    MEETING = "MEETING"
    INTERVIEW = "INTERVIEW"
    GENERAL = "GENERAL"


class AudioSource(str, Enum):
    """Audio speaker sources."""

    ME = "ME"
    OTHERS = "OTHERS"


class SessionStatus(str, Enum):
    """Persisted session lifecycle states."""

    INCOMPLETE = "incomplete"
    COMPLETED = "completed"
    RECOVERED = "recovered"


class ProcessSource(str, Enum):
    """Processes that can emit persisted events."""

    GUI = "GUI"
    AUDIO = "AUDIO"
    ASR = "ASR"
    DISCUSSION = "DISCUSSION"
    WRITER = "WRITER"


class EventType(str, Enum):
    """Persisted event types."""

    SESSION_START = "SESSION_START"
    PAUSE_START = "PAUSE_START"
    PAUSE_END = "PAUSE_END"
    STOP_REQUESTED = "STOP_REQUESTED"
    SESSION_COMPLETED = "SESSION_COMPLETED"
    SOURCE_DISCONNECTED = "SOURCE_DISCONNECTED"
    SOURCE_RECONNECTED = "SOURCE_RECONNECTED"
    ASR_LAG_STARTED = "ASR_LAG_STARTED"
    ASR_LAG_ENDED = "ASR_LAG_ENDED"
    ANALYSIS_PAUSED = "ANALYSIS_PAUSED"
    ANALYSIS_RESUMED = "ANALYSIS_RESUMED"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"
    WORKER_EXITED = "WORKER_EXITED"
    WORKER_RESTARTED = "WORKER_RESTARTED"
    STORAGE_FAILED = "STORAGE_FAILED"
    FORCE_CLOSE_REQUESTED = "FORCE_CLOSE_REQUESTED"
    SESSION_RECOVERED = "SESSION_RECOVERED"


class MessageType(str, Enum):
    """Inter-process message types."""

    WORKER_START = "WORKER_START"
    WORKER_READY = "WORKER_READY"
    WORKER_PAUSE = "WORKER_PAUSE"
    WORKER_RESUME = "WORKER_RESUME"
    WORKER_STOP = "WORKER_STOP"
    WORKER_STOPPED = "WORKER_STOPPED"
    WORKER_ERROR = "WORKER_ERROR"
    AUDIO_LEVEL = "AUDIO_LEVEL"
    SOURCE_DISCONNECTED = "SOURCE_DISCONNECTED"
    SOURCE_RECONNECTED = "SOURCE_RECONNECTED"
    TRANSCRIPT_PARTIAL = "TRANSCRIPT_PARTIAL"
    TRANSCRIPT_COMMITTED = "TRANSCRIPT_COMMITTED"
    ASR_STATUS = "ASR_STATUS"
    DISCUSSION_ANALYZE = "DISCUSSION_ANALYZE"
    DISCUSSION_STATE_REPLACED = "DISCUSSION_STATE_REPLACED"
    DISCUSSION_STATUS = "DISCUSSION_STATUS"
    WRITER_OPEN_SESSION = "WRITER_OPEN_SESSION"
    EVENT_APPENDED = "EVENT_APPENDED"
    WRITER_FLUSH = "WRITER_FLUSH"
    WRITER_FINALIZE = "WRITER_FINALIZE"
    WRITER_SHUTDOWN = "WRITER_SHUTDOWN"
    WRITER_ACK = "WRITER_ACK"
    WRITER_FORCE_CLOSE_RESULT = "WRITER_FORCE_CLOSE_RESULT"
    WRITER_FATAL = "WRITER_FATAL"
